build:
  stage: build
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build ./docker --pull --build-arg GITLAB_API_KEY --target ilias -t $CI_REGISTRY_IMAGE/ilias:latest
    - docker push $CI_REGISTRY_IMAGE/ilias:latest
    - docker build ./docker --pull --build-arg GITLAB_API_KEY --target nginx -t $CI_REGISTRY_IMAGE/nginx:latest
    - docker push $CI_REGISTRY_IMAGE/nginx:latest
    - docker build ./docker --pull --build-arg GITLAB_API_KEY --target cron -t $CI_REGISTRY_IMAGE/cron:latest
    - docker push $CI_REGISTRY_IMAGE/cron:latest
    - docker build ./docker --pull --build-arg GITLAB_API_KEY --target ilserver -t $CI_REGISTRY_IMAGE/ilserver:latest
    - docker push $CI_REGISTRY_IMAGE/ilserver:latest
  after_script:
    - docker logout $CI_REGISTRY
  only:
    - tags