<?php

/**
 * This file is part of ILIAS, a powerful learning management system
 * published by ILIAS open source e-Learning e.V.
 *
 * ILIAS is licensed with the GPL-3.0,
 * see https://www.gnu.org/licenses/gpl-3.0.en.html
 * You should have received a copy of said license along with the
 * source code, too.
 *
 * If this is not the case or you just want to try ILIAS, you'll find
 * us at:
 * https://www.ilias.de
 * https://github.com/ILIAS-eLearning
 *
 *********************************************************************/

declare(strict_types=1);

require_once __DIR__ . "/../vendor/autoload.php";

use ILIAS\DI\Container;
use ILIAS\Plugin\OnlyOffice\StorageService\StorageService;
use ILIAS\Plugin\OnlyOffice\StorageService\Infrastructure\File\ilDBFileVersionRepository;
use ILIAS\Plugin\OnlyOffice\StorageService\Infrastructure\File\ilDBFileRepository;
use ILIAS\Plugin\OnlyOffice\StorageService\Infrastructure\File\ilDBFileChangeRepository;
use ILIAS\Data\UUID\Uuid;
use Matrix\Exception;
use ILIAS\Data\UUID\Factory as UUIDFactory;

/**
 * Handles the callback generated by ONLYOFFICE Docs
 * Called by save.php
 */
class xonoCallbackHandler
{
    protected Container $dic;
    protected StorageService $storage_service;
    protected string $file_data;
    protected Uuid $uuid;
    protected int $file_id;
    protected int $editor_id;
    protected string $file_extension;
    protected string $changes_object;
    protected string $serverVersion;
    protected string $change_data;
    protected string $change_extension;
    protected string $fileUrl;
    protected string $changeUrl;

    /**
     * @throws Exception if the data cannot be fetched
     */
    public function __construct(
        Container $dic,
        string $uuid,
        int $file_id,
        array $data
    ) {
        $this->dic = $dic;
        $this->uuid = (new UUIDFactory())->fromString($uuid);
        $this->file_id = $file_id;

        $this->fileUrl = $data["url"];
        $this->editor_id = $data["users"][0];
        $this->serverVersion = $data["history"]["serverVersion"];
        $this->changeUrl = $data["changesurl"];
        $this->changes_object = json_encode($data["history"]["changes"], JSON_THROW_ON_ERROR);
        $this->file_extension = pathinfo($this->fileUrl, PATHINFO_EXTENSION);
        $this->change_extension = pathinfo($this->changeUrl, PATHINFO_EXTENSION);
        $this->fetchData();
        if (!$this->file_data || !$this->change_data) {
            $this->dic->logger()->root()->error("Data could not be fetched - file data url:" . $this->fileUrl . " - change data url: " . $this->changeUrl);
            throw new Exception("Data could not be fetched");
        }

        $this->afterConstructor();

    }

    protected function afterConstructor(): void
    {
        $this->storage_service = new StorageService(
            $this->dic,
            new ilDBFileVersionRepository(),
            new ilDBFileRepository(),
            new ilDBFileChangeRepository()
        );
    }

    public function handleCallback(): bool
    {
        try {
            // Upload the new file
            $this->storage_service->updateFileFromUpload(
                $this->file_data,
                $this->file_id,
                $this->uuid,
                $this->editor_id,
                $this->file_extension,
                $this->changes_object,
                $this->serverVersion,
                $this->change_data,
                $this->change_extension
            );
            return true;
        } catch (ilDateTimeException) {
            return false;
        }
    }

    protected function fetchData(): void
    {
        $this->file_data = file_get_contents($this->fileUrl);
        $this->change_data = file_get_contents($this->changeUrl);
    }
}
